### ISSUE TITLE
bundler

### ISSUE THREAD

**Issue by Roxxik** [Und0ne/appoint-server#1]
Ich kenne mich ehrlich gesagt nicht so gut mit dem Deployment von Ruby aus, aber die Anleitung zum installieren funktioniert nicht wenn nicht vorher

```
gem install bundle
```

und

```
PATH=$PATH:$HOME/.gem/ruby/<version>/bin
```

ausgeführt werden

**Comment by kindermann-dev** [comment]
Installation von Bundler hinzugefügt: de2db13
Beim Path ist wohl bei der Installation vom ruby was schief gegangen, ist aber kein Fehler.
